<?php
DEFINE ('COOKIE_TAG', '?##08-029_?(#002)00046?@');
DEFINE ('TAIL_SALT', '*(10021)?0007258_0045');
/* 
    Cookie tag generated by converting a valuable string to a numberformat
*/
class CookiesHandler{
    private $_sessionId;
    private $_newCookie;

    function __construct($sessionId)
    {
        $this->_sessionId = $sessionId;
        $this->_setNewCookie();
    }
    private function _setNewCookie(){
        $this->_newCookie = COOKIE_TAG.$this->_sessionId.TAIL_SALT;
    }
    public function getCoookie(){
        return $this->_newCookie;
    }
}
